backend:
  name: git-gateway #Open source API -> acts as proxy bt auth users and ur repo
  branch: master #Branch to update
publish_mode: editorial_workflow #adds interface for drafting, reviewing and approving
media_folder: 'static/images/uploads' #Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'
media_library:
  name: cloudinary
  config:
    cloud_name: varnebla
    api_key: 384885582618967
    output_filename_only: false
    config:
      default_transformations:
        - - fetch_format: auto
            width: 200
            quality: auto
            crop: scale
collections:
  - name: 'posts' # Used in routes, e.g., /admin/collections/posts
    label: 'Posts' #Used in the UI
    folder: 'content/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}'
    extension: 'md'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Abstract', name: 'abstract', widget: 'text' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Imagen', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          field:
            { label: 'Tag', name: 'tag', widget: 'string', default: 'tag' },
        }
      - {
          label: 'Tema',
          name: 'topic',
          widget: 'select',
          options: ['art', 'music', 'travel'],
        }
      - { label: 'Contenido', name: 'content', widget: 'markdown' }
  # - name: 'topics'
  #   label: 'Temas'
  #   folder: 'content/topics' # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   extension: 'md'
  #   identifier_field: 'name'
  #   fields:
  #     - { label: 'Tema', name: 'name', widget: 'string' }
  #     - { label: 'Descripción', name: 'description', widget: 'text' }
  #     - { label: 'Imagen', name: 'thumbnail', widget: 'image' }
  - name: 'pages'
    label: 'Páginas'
    files:
      - name: 'landing'
        label: 'Landing'
        file: 'content/landing.md'
        fields:
          # - { label: 'Eslogan', name: 'slogan', widget: 'string' }
          # - label: 'Temas'
          #   name: 'topics'
          #   widget: 'list'
          #   fields:
          #     - { label: 'Tema', name: 'name', widget: 'string' }
          #     - { label: 'Descripción', name: 'description', widget: 'text' }
          #     - { label: 'Imagen', name: 'thumbnail', widget: 'image' }
          # - { label: 'Contacto', name: 'contact', widget: 'markdown' }
          - {
              label: 'Imágen principal presentación',
              name: 'presentation_picture',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Imágen secundaria presentación',
              name: 'presentation_secondary_picture',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Imágen introducción',
              name: 'intro_picture',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Imágen cultura y arte 1',
              name: 'art_primary_picture',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Imágen cultura y arte 2',
              name: 'art_secondary_picture',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Imágen cultura y arte 3',
              name: 'art_tertiary_picture',
              widget: 'image',
              required: true,
            }
      - name: 'about'
        label: 'Sobre mí'
        file: 'content/about.md'
        fields:
          - { label: 'Imagen', name: 'profile_picture', widget: 'image' }
          - { label: 'Contenido', name: 'about_content', widget: 'markdown' }
